PRODUCT_BRAND ?= TheParasiteProject

CUSTOM_BUILD_DATE := $(shell date +%Y%m%d-%H%M)
CUSTOM_BUILD_DATE_UTC := $(shell date '+%Y-%m-%d %H:%M UTC %s')

CUSTOM_PLATFORM_VERSION := 14.0

CUSTOM_VERSION := TheParasiteProject_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)
CUSTOM_VERSION_PROP := android14-qpr1
