#!/bin/bash

GREEN="\033[0;32m"

export Changelog=changelog.md

DEVICE=$(echo $TARGET_PRODUCT | sed -e 's/aosp_//g')

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

echo -e "# $DEVICE\n" >> $Changelog;

for i in $(seq 5);
do
	export After_Date=`/bin/date --date="$i days ago" +%m-%d-%Y`
	k=$(expr $i - 1)
	export Until_Date=`/bin/date --date="$k days ago" +%m-%d-%Y`
	echo -e "### $Until_Date\n" >> $Changelog;
	# Cycle through every repo to find commits between 2 dates
	while read path;
	do
		CLOG=$(git --git-dir ./${path}/.git log --oneline --after=$After_Date --until=$Until_Date --pretty=tformat:"%x2A %h  %s  [%an]" --abbrev-commit --abbrev=7);
		if [ -n "$CLOG" ]; then
			echo -e "#### ${path}\n\n${CLOG}\n" >> $Changelog;
		fi
	done < ./.repo/project.list
done

cp $Changelog ${OUT_DIR:-./out}/target/product/$DEVICE/
rm $Changelog
echo -e "${GREEN}Done generating changelog for $DEVICE"
